### ISSUE TITLE
45% of the time decoding lossy images is spent in `fill_single`

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-webp#11]
It seems YUV to RGB conversion is now the bottleneck, accounting for 45% of the time.

Profile showing it: https://share.firefox.dev/46lRpxt

Test image: [test_lossy.webp.gz](https://github.com/image-rs/image-webp/files/12837929/test_lossy.webp.gz)

Measured on commit 18867eceaa709a6e3a1f4ec734344e3a2293c885

Code used: 

```rust
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let input = std::env::args().nth(1).unwrap();
    let f = std::fs::File::open(input)?;
    let reader = std::io::BufReader::new(f);
    let mut decoder = webp::WebPDecoder::new(reader)?;
    let mut output = vec![0u8; decoder.output_buffer_size()];
    let _img = decoder.read_image(&mut output)?;
    Ok(())
}
```

**Comment by Shnatsel** [comment]
The original code uses the `_mm_mulhi_epu16` SIMD intrinsic, which is also available in Rust as `core::arch::x86_64::_mm_mulhi_epu16`. 

It was introduced in SSE2, which is part of the x86_64 baseline. This is probably why the original code uses it, as opposed to more straightforward conversions.

Also, a single SSE lane is `i16x8`. This lets us process two pixels in one instruction, since we need 4 multiplications for each RGB pixel. It may be a good idea to change the signature of the function to process two pixels at once instead of just one.

**Comment by okaneco** [comment]
I looked into the clipping code a little.

It seems we can refactor the clip function, and that it optimizes better when calculating the channels up front into a `[u8; 3]` before saving. I haven't benchmarked it yet, but llvm-mca on godbolt reports less instructions and cycles (just started using this tool, it doesn't replace benching but I also don't have a feel for what a "significant enough" change is yet).
https://rust.godbolt.org/z/s9d18Y5EP
```rust
fn clip(v: i32) -> u8 {
    (v.max(0) >> YUV_FIX2).min(255) as u8
}
```

Sample code to show the functions have equivalent results:
https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=ca455fb94c6e1588e7f83845c2732afe

Trying to use `std::simd` for clamping doesn't work well I think because of an upstream LLVM issue with truncating saturating casts for 4-length vectors. It generates a lot of unnecessary instructions but could one day be faster and maybe kick in for the scalar code we have.
https://rust.godbolt.org/z/a9sqvnPo4

**Comment by fintelia** [comment]
I think it might be more efficient to stop operating in terms of pixels held in 4-length vectors and instead have each vector hold single channels. So one vector of 16x Y values, another with 8x U, a third with 8x V. Then the output would be 16x each of R, G, and B.

**Comment by okaneco** [comment]
That makes sense. I think two pixels also makes sense as the base unit to work with because of the chroma plane being half-width.

I wrote out a sketch based on that suggestion and ended up with the code on the left. Within `fill_rgb`, I was manually slicing 16 pixels at a time, then 2, then fill single as fallback for the remainder of the row.
https://rust.godbolt.org/z/1jTabjo3q

When I replaced array indexing with iterators/chunks, I got vectorized code and realized I could convert it to the right. It's not great output but I see ~7% improvement on the benchmarks in `image`.
https://github.com/okaneco/image-webp/commit/c10fd553ba1036d837a1d2c35a2ab25c94faf74a

An SOA-style solution might perform better but I was having trouble wrapping my head around a way to write it efficiently.

**Comment by okaneco** [comment]
I tried 3 different approaches for improving filling rows:
1. 2 pixels at once [okaneco@`5c84545`](https://github.com/okaneco/image-webp/commit/5c8454583689fa70b246683cb201c77db213f15b#diff-89c0853308bc874aff5e9c034d0ea9d4857dd3c734f705f6753c59916f04d2b8)
2. Calculating chunks of componentwise Y, u, v, R, G, B https://github.com/okaneco/image-webp/commit/aca63209eccadc1a309e9e6d8af7a051c47cca18
3. Fill 2x2 pixel blocks in consecutive rows to reduce coefficient calculations further (1 calculation per 4 pixels, instead of the current 1 calculation per 1 pixel) [okaneco@`8f2e662`](https://github.com/okaneco/image-webp/commit/8f2e662bd360446d673fe55dcfd4dd4819bb3fac#diff-89c0853308bc874aff5e9c034d0ea9d4857dd3c734f705f6753c59916f04d2b8R935)

"2 pixels at once" was fastest when plugged into the `image` benchmarks (it's also the easiest implementation to follow).

There doesn't seem much to be gained by saving temporary values if we're able to get auto-vectorization with 2 pixels at a time and write those results immediately.
- For `#2`, code was faster at doing 32 pixels at a time than 16, 8, etc., but you're still left with a remainder of at most 31 pixels to convert at the end of a row. Writing each pixel as it was calculated was faster than writing to a temporary buffer and copying that to the output. Trying to reduce this further ends up with scalarized "2 pixels at a time" output.
- For `#3`, keeping in memory and accessing two rows of `self.ybuf` and the output buffer seemed to outweigh anything gained by doing one less calculation of the coeffecients. And there's still a remainder row to fill with odd heights

**Comment by fintelia** [comment]
The "2 pixels at once" version was merged in #13. Further optimizations are of course welcome, but based on the investigation thus far I wouldn't expect any huge further improvements from SIMD.

Another direction would be to try making a multithreaded version. Looking at the current code, it seems like it would be reasonably straightforward to use `rayon` to process rows in parallel

**Comment by Shnatsel** [comment]
It seems the original WebP implementation faced the same issue, and they ended up writing optimized routines with output that isn't bit-by-bit identical to the baseline. I think we are holding ourselves back here by adhering to `dwebp -nofancy -noasm` this strictly, when `dwebp` itself doesn't do that by default.

@fintelia would you be open to a faster implementation that is not bit-exact, but keeping the slower bit-exact version around as an equivalent of `dwebp -nofancy -noasm` for debugging and use cases where bit-exact output is needed?

**Comment by Shnatsel** [comment]
I've profiled the decoding process again on a large file, and it seems colorspace conversion is no longer a big contributor: https://share.firefox.dev/49ZwlOo

Closing as completed :tada:
