### ISSUE TITLE
Crafted images in 400 bytes or less take over a minute to decode

### ISSUE THREAD

**Issue by Shnatsel** [image-rs/image-webp#38]
Found with the fuzzer. Several test cases that take over 60s to decode, ranging from ~90 to ~400 bytes: [webp_slow_to_decode.tar.gz](https://github.com/image-rs/image-webp/files/13782119/webp_slow_to_decode.tar.gz)

Tested on commit cc5ec05d1dddfe8a389c738c34c9789eefa08d32

**Comment by fintelia** [comment]
Did some investigation of the 86-byte test case...

The core issue seems to be that this library believes the file is a valid WebP image. Once you account for the claimed 11024x13994 image dimensions, the 34 second decoding time (on my machine) works out to a not totally unreasonable 17 MB/s decoding speed.

From what I've gathered so far, the reason the code's OK with such a small file encoding so large an image is because the reader simply treats a truncated bitstream as containing infinitely more zero bytes:

https://github.com/image-rs/image-webp/blob/67a0f4eb181525f1cccbf0a73c58cd41977f74cf/src/vp8.rs#L731-L736

**Comment by Shnatsel** [comment]
FWIW `dwebp` just errors out with "not enough data" instead.

**Comment by Shnatsel** [comment]
I don't think treating the incoming bitstream as containing zero bytes is even needed for partial decoding. If the image is truncated, we will decode all the valid parts and write them to the input slice, and then once we raise an error about a premature EOF the valid data stays there. So I think we should just raise an error on an unexpected EOF.

**Comment by Shnatsel** [comment]
I'll do more fuzzing once this is fixed, because right now I am only getting ~50 executions per second per core.

**Comment by Shnatsel** [comment]
I am getting at around 10,000 executions per second per core on the fuzzer. Nice!
